import 'dart:io';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../../core/services/database_repository.dart';
import '../../../core/services/storage_repository.dart';
import '../../../core/models/chat_message.dart';
import '../../auth/data/auth_repository.dart';

part 'chat_providers.g.dart';

@riverpod
Stream<List<ChatMessage>> chatMessages(Ref ref, String groupId) {
  return ref.watch(databaseRepositoryProvider).streamMessages(groupId, limit: 100);
}

@riverpod
class ChatController extends _$ChatController {
  @override
  FutureOr<void> build() {
    // Idle state
  }

  ChatMessage? _replyTo;
  ChatMessage? get replyTo => _replyTo;

  void setReplyTo(ChatMessage? message) {
    _replyTo = message;
    // We don't necessarily need to trigger a state change for the whole controller,
    // but we could notify listeners if we had a dedicated state object.
    // For now, simple getter is fine for the composer.
  }

  Future<void> sendTextMessage({
    required String groupId,
    required String text,
  }) async {
    final user = ref.read(authRepositoryProvider).currentUser;
    if (user == null) return;

    final message = ChatMessage(
      id: '', // Push ID will be generated by Firebase
      groupId: groupId,
      senderId: user.uid,
      senderName: user.displayName ?? 'User',
      senderPhotoUrl: user.photoURL,
      text: text,
      ts: DateTime.now().millisecondsSinceEpoch,
      replyToId: _replyTo?.id,
      replySenderName: _replyTo?.senderName,
      replyPreview: _replyTo?.text,
    );

    _replyTo = null; // Clear reply context after sending

    // Note: To implement "True" optimistic UI, we would need a state-based collection
    // that combines the real stream with local "pending" messages.
    // Given the user wants "instantly", I'll be focusing on making the UI feel fast.
    
    await ref.read(databaseRepositoryProvider).sendMessage(message);
  }

  Future<void> sendPhotoMessage({
    required String groupId,
    required File file,
    String? caption,
  }) async {
    state = const AsyncValue.loading();
    
    state = await AsyncValue.guard(() async {
      final user = ref.read(authRepositoryProvider).currentUser;
      if (user == null) return;

      // 1. Upload to Storage
      final downloadUrl = await ref.read(storageRepositoryProvider).uploadChatPhoto(
        groupId: groupId,
        file: file,
      );

      // 2. Send Message Metadata
      final message = ChatMessage(
        id: '',
        groupId: groupId,
        senderId: user.uid,
        senderName: user.displayName ?? 'User',
        senderPhotoUrl: user.photoURL,
        text: caption ?? '',
        photoUrl: downloadUrl,
        contentType: 'image/jpeg', // simplified
        ts: DateTime.now().millisecondsSinceEpoch,
        replyToId: _replyTo?.id,
        replySenderName: _replyTo?.senderName,
        replyPreview: _replyTo?.text,
      );

      _replyTo = null;
      await ref.read(databaseRepositoryProvider).sendMessage(message);
    });
  }
}
