import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../../core/services/meeting_repository.dart';
import '../../../../core/models/meeting_proposal.dart';
import '../../../../features/auth/data/auth_repository.dart';

class CreateProposalDialog extends ConsumerStatefulWidget {
  final String groupId;
  final String baseColor;

  const CreateProposalDialog({super.key, required this.groupId, required this.baseColor});

  @override
  ConsumerState<CreateProposalDialog> createState() => _CreateProposalDialogState();
}

class _CreateProposalDialogState extends ConsumerState<CreateProposalDialog> {
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final List<DateTime> _selectedDates = [];
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    super.dispose();
  }

  Future<void> _addDate() async {
    final date = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: ColorScheme.light(
              primary: Color(int.parse(widget.baseColor)),
              onPrimary: Colors.white,
              onSurface: Colors.black87,
            ),
          ),
          child: child!,
        );
      },
    );

    if (date != null && mounted) {
      final time = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
      );

      if (time != null) {
        setState(() {
          _selectedDates.add(DateTime(
            date.year,
            date.month,
            date.day,
            time.hour,
            time.minute,
          ));
          _selectedDates.sort();
        });
      }
    }
  }

  Future<void> _submit() async {
    if (_titleController.text.trim().isEmpty || _selectedDates.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please add a title and at least one date option')),
      );
      return;
    }

    setState(() => _isLoading = true);
    try {
      final currentUser = ref.read(authRepositoryProvider).currentUser;
      final proposal = MeetingProposal(
        id: '', // Generated by Firestore
        groupId: widget.groupId,
        title: _titleController.text.trim(),
        description: _descController.text.trim(),
        creatorId: currentUser?.uid ?? '',
        proposedDates: _selectedDates,
        votes: {},
        createdAt: DateTime.now().millisecondsSinceEpoch,
      );

      await ref.read(meetingRepositoryProvider).createProposal(proposal);
      if (mounted) Navigator.pop(context);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      backgroundColor: Colors.white,
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Propose Gathering',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: _titleController,
                decoration: InputDecoration(
                  labelText: 'Title',
                  hintText: 'e.g. Summer BBQ',
                  filled: true,
                  fillColor: Colors.grey[100],
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
                ),
              ),
              const SizedBox(height: 12),
              TextField(
                controller: _descController,
                maxLines: 2,
                decoration: InputDecoration(
                  labelText: 'Description (Optional)',
                  hintText: 'Bring your own drinks!',
                  filled: true,
                  fillColor: Colors.grey[100],
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
                ),
              ),
              const SizedBox(height: 24),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text('Date Options', style: TextStyle(fontWeight: FontWeight.bold)),
                  TextButton.icon(
                    onPressed: _addDate,
                    icon: const Icon(Icons.add_circle_outline, size: 20),
                    label: const Text('Add Option'),
                    style: TextButton.styleFrom(foregroundColor: Color(int.parse(widget.baseColor))),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              if (_selectedDates.isEmpty)
                Center(
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Text('No dates added yet', style: TextStyle(color: Colors.grey[400], fontSize: 13)),
                  ),
                )
              else
                ..._selectedDates.map((date) => Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  decoration: BoxDecoration(
                    color: Colors.grey[50],
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: Colors.grey[200]!),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        DateFormat('EEE, MMM d • HH:mm').format(date),
                        style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
                      ),
                      IconButton(
                        icon: const Icon(Icons.remove_circle_outline, color: Colors.redAccent, size: 20),
                        onPressed: () => setState(() => _selectedDates.remove(date)),
                      ),
                    ],
                  ),
                )),
              const SizedBox(height: 32),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(int.parse(widget.baseColor)),
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                    elevation: 0,
                  ),
                  child: _isLoading 
                      ? const CircularProgressIndicator(color: Colors.white)
                      : const Text('POST PROPOSAL', style: TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
